[2024-10-14T17:13:46.300-0600] {processor.py:186} INFO - Started process (PID=54997) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:13:46.301-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:13:46.307-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:13:46.307-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:13:47.782-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:13:47.766-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:13:47.797-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:13:48.059-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.771 seconds
[2024-10-14T17:14:18.130-0600] {processor.py:186} INFO - Started process (PID=55102) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:14:18.152-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:14:18.155-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:14:18.155-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:14:19.495-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:14:19.475-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:14:19.526-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:14:20.102-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.982 seconds
[2024-10-14T17:14:50.330-0600] {processor.py:186} INFO - Started process (PID=55202) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:14:50.341-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:14:50.344-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:14:50.344-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:14:50.924-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:14:50.915-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:14:50.933-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:14:51.280-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.956 seconds
[2024-10-14T17:15:21.423-0600] {processor.py:186} INFO - Started process (PID=55288) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:15:21.722-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:15:21.725-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:15:21.725-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:15:22.433-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:15:22.416-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:15:22.448-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:15:22.640-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.226 seconds
[2024-10-14T17:15:54.525-0600] {processor.py:186} INFO - Started process (PID=55380) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:15:54.526-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:15:54.539-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:15:54.538-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:15:56.087-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:15:56.069-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:15:56.116-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:15:56.897-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 2.389 seconds
[2024-10-14T17:16:27.571-0600] {processor.py:186} INFO - Started process (PID=55472) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:16:27.572-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:16:27.577-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:16:27.576-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:16:28.483-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:16:28.471-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:16:28.499-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:16:28.863-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.308 seconds
[2024-10-14T17:16:59.746-0600] {processor.py:186} INFO - Started process (PID=55564) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:16:59.751-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:16:59.753-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:16:59.753-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:17:00.264-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:17:00.252-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:17:00.273-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:17:00.620-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.880 seconds
[2024-10-14T17:17:30.876-0600] {processor.py:186} INFO - Started process (PID=55659) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:17:30.884-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:17:30.886-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:17:30.886-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:17:31.327-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:17:31.320-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:17:31.337-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:17:31.581-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.713 seconds
[2024-10-14T17:18:02.438-0600] {processor.py:186} INFO - Started process (PID=55757) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:18:02.439-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:18:02.441-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:18:02.441-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:18:02.939-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:18:02.931-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:18:02.944-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:18:03.125-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.693 seconds
[2024-10-14T17:18:33.643-0600] {processor.py:186} INFO - Started process (PID=55849) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:18:33.842-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:18:33.844-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:18:33.843-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:18:34.287-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:18:34.281-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:18:34.295-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:18:34.786-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.150 seconds
[2024-10-14T17:19:05.509-0600] {processor.py:186} INFO - Started process (PID=55941) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:19:05.511-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:19:05.514-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:19:05.514-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:19:06.092-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:19:06.087-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:19:06.097-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:19:06.342-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.850 seconds
[2024-10-14T17:19:36.667-0600] {processor.py:186} INFO - Started process (PID=56033) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:19:36.694-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:19:36.701-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:19:36.696-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:19:39.473-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:19:39.455-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:19:39.489-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:19:41.250-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 4.601 seconds
[2024-10-14T17:20:11.662-0600] {processor.py:186} INFO - Started process (PID=56137) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:20:11.664-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:20:11.678-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:20:11.678-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:20:12.388-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:20:12.383-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 60, in <module>
    fetch_news_task >> save_to_s3_task
NameError: name 'fetch_news_task' is not defined
[2024-10-14T17:20:12.393-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:20:12.884-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.326 seconds
[2024-10-14T17:20:40.935-0600] {processor.py:186} INFO - Started process (PID=56224) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:20:40.939-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:20:40.947-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:20:40.946-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:20:41.425-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:20:41.421-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:20:41.430-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:20:41.615-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.688 seconds
[2024-10-14T17:21:12.033-0600] {processor.py:186} INFO - Started process (PID=56318) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:21:12.038-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:21:12.041-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:21:12.040-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:21:12.508-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:21:12.503-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:21:12.512-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:21:13.028-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.001 seconds
[2024-10-14T17:21:43.644-0600] {processor.py:186} INFO - Started process (PID=56420) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:21:43.653-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:21:43.656-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:21:43.656-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:21:44.034-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:21:44.030-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:21:44.037-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:21:44.224-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.586 seconds
[2024-10-14T17:22:14.321-0600] {processor.py:186} INFO - Started process (PID=56514) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:22:14.323-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:22:14.324-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:22:14.324-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:22:14.888-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:22:14.883-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:22:14.893-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:22:15.773-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.458 seconds
[2024-10-14T17:22:45.897-0600] {processor.py:186} INFO - Started process (PID=56606) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:22:45.898-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:22:45.902-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:22:45.901-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:22:46.275-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:22:46.270-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:22:46.282-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:22:46.459-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.570 seconds
[2024-10-14T17:23:16.582-0600] {processor.py:186} INFO - Started process (PID=56698) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:23:16.594-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:23:16.596-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:23:16.596-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:23:17.695-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:23:17.679-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:23:17.709-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:23:17.964-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.398 seconds
[2024-10-14T17:23:48.782-0600] {processor.py:186} INFO - Started process (PID=56790) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:23:48.803-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:23:48.806-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:23:48.805-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:23:49.184-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:23:49.180-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:23:49.187-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:23:49.347-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.581 seconds
[2024-10-14T17:24:19.718-0600] {processor.py:186} INFO - Started process (PID=56882) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:24:19.721-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:24:19.728-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:24:19.727-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:24:20.299-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:24:20.293-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:24:20.305-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:24:20.503-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.808 seconds
[2024-10-14T17:24:50.594-0600] {processor.py:186} INFO - Started process (PID=56974) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:24:50.600-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:24:50.604-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:24:50.603-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:24:50.954-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:24:50.950-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:24:50.957-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:24:51.468-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.883 seconds
[2024-10-14T17:25:21.561-0600] {processor.py:186} INFO - Started process (PID=57066) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:25:21.575-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:25:21.577-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:25:21.576-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:25:21.917-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:25:21.912-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:25:21.921-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:25:22.404-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.849 seconds
[2024-10-14T17:25:52.796-0600] {processor.py:186} INFO - Started process (PID=57158) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:25:52.797-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:25:52.798-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:25:52.798-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:25:53.115-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:25:53.111-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:25:53.118-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:25:53.595-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.805 seconds
[2024-10-14T17:26:23.762-0600] {processor.py:186} INFO - Started process (PID=57250) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:26:23.770-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:26:23.772-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:26:23.771-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:26:24.105-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:26:24.101-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:26:24.108-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:26:24.880-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.123 seconds
[2024-10-14T17:26:55.018-0600] {processor.py:186} INFO - Started process (PID=57348) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:26:55.019-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:26:55.023-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:26:55.022-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:26:55.332-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:26:55.328-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:26:55.335-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:26:55.905-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.893 seconds
[2024-10-14T17:27:25.982-0600] {processor.py:186} INFO - Started process (PID=57440) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:27:25.984-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:27:25.986-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:27:25.986-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:27:26.291-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:27:26.288-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:27:26.295-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:27:26.470-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.493 seconds
[2024-10-14T17:27:56.548-0600] {processor.py:186} INFO - Started process (PID=57532) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:27:56.549-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:27:56.551-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:27:56.551-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:27:56.879-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:27:56.875-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:27:56.882-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:27:57.466-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.924 seconds
[2024-10-14T17:28:27.613-0600] {processor.py:186} INFO - Started process (PID=57624) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:28:27.623-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:28:27.626-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:28:27.626-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:28:27.949-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:28:27.946-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:28:27.952-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:28:28.230-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.622 seconds
[2024-10-14T17:28:58.373-0600] {processor.py:186} INFO - Started process (PID=57716) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:28:58.393-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:28:58.395-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:28:58.395-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:28:58.699-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:28:58.696-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:28:58.703-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:28:58.933-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.565 seconds
[2024-10-14T17:29:29.202-0600] {processor.py:186} INFO - Started process (PID=57808) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:29:29.223-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:29:29.226-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:29:29.225-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:29:29.525-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:29:29.522-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:29:29.528-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:29:29.718-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.521 seconds
[2024-10-14T17:29:59.873-0600] {processor.py:186} INFO - Started process (PID=57900) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:29:59.920-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:29:59.922-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:29:59.922-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:30:00.745-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:30:00.731-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:30:00.760-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:30:00.974-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.108 seconds
[2024-10-14T17:30:31.160-0600] {processor.py:186} INFO - Started process (PID=57992) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:30:31.161-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:30:31.163-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:30:31.162-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:30:31.575-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:30:31.571-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:30:31.578-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:30:32.141-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.987 seconds
[2024-10-14T17:31:02.225-0600] {processor.py:186} INFO - Started process (PID=58084) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:31:02.234-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:31:02.236-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:31:02.236-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:31:02.647-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:31:02.643-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:31:02.650-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:31:03.206-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.986 seconds
[2024-10-14T17:31:33.296-0600] {processor.py:186} INFO - Started process (PID=58176) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:31:33.311-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:31:33.314-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:31:33.313-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:31:33.703-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:31:33.700-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:31:33.707-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:31:34.267-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.977 seconds
[2024-10-14T17:32:04.371-0600] {processor.py:186} INFO - Started process (PID=58271) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:32:04.372-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:32:04.374-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:32:04.374-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:32:04.951-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:32:04.946-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:32:04.954-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:32:05.121-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.756 seconds
[2024-10-14T17:32:35.462-0600] {processor.py:186} INFO - Started process (PID=58365) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:32:35.463-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:32:35.464-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:32:35.464-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:32:35.766-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:32:35.763-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:32:35.769-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:32:36.016-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.560 seconds
[2024-10-14T17:33:06.266-0600] {processor.py:186} INFO - Started process (PID=58457) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:33:06.270-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:33:06.272-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:33:06.272-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:33:06.605-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:33:06.602-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:33:06.608-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:33:06.781-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.521 seconds
[2024-10-14T17:33:36.966-0600] {processor.py:186} INFO - Started process (PID=58549) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:33:36.967-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:33:36.969-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:33:36.969-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:33:37.338-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:33:37.331-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:33:37.342-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:33:37.522-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.563 seconds
[2024-10-14T17:34:07.631-0600] {processor.py:186} INFO - Started process (PID=58641) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:34:07.640-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:34:07.643-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:34:07.642-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:34:08.021-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:34:08.010-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:34:08.029-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:34:08.267-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.642 seconds
[2024-10-14T17:34:39.910-0600] {processor.py:186} INFO - Started process (PID=58733) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:34:39.917-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:34:39.919-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:34:39.919-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:34:40.269-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:34:40.265-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:34:40.273-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:34:41.730-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.826 seconds
[2024-10-14T17:35:12.610-0600] {processor.py:186} INFO - Started process (PID=58831) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:35:12.612-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:35:12.614-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:35:12.614-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:35:12.957-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:35:12.954-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:35:12.960-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:35:13.125-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.521 seconds
[2024-10-14T17:35:43.711-0600] {processor.py:186} INFO - Started process (PID=58929) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:35:43.712-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:35:43.714-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:35:43.714-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:35:44.038-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:35:44.035-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:35:44.041-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:35:44.216-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.516 seconds
[2024-10-14T17:36:14.705-0600] {processor.py:186} INFO - Started process (PID=59021) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:36:14.716-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:36:14.720-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:36:14.720-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:36:15.080-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:36:15.076-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:36:15.083-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:36:15.246-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.580 seconds
[2024-10-14T17:36:46.263-0600] {processor.py:186} INFO - Started process (PID=59113) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:36:46.265-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:36:46.269-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:36:46.269-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:36:46.596-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:36:46.592-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:36:46.600-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:36:46.762-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.514 seconds
[2024-10-14T17:37:17.757-0600] {processor.py:186} INFO - Started process (PID=59205) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:37:17.765-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:37:17.768-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:37:17.767-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:37:18.103-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:37:18.100-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:37:18.106-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:37:18.269-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.518 seconds
[2024-10-14T17:37:49.344-0600] {processor.py:186} INFO - Started process (PID=59303) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:37:49.357-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:37:49.360-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:37:49.360-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:37:49.876-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:37:49.870-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:37:49.887-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:37:50.592-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.254 seconds
[2024-10-14T17:38:20.756-0600] {processor.py:186} INFO - Started process (PID=59396) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:38:20.757-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:38:20.759-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:38:20.759-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:38:21.093-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:38:21.090-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:38:21.096-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:38:21.684-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.933 seconds
[2024-10-14T17:38:51.869-0600] {processor.py:186} INFO - Started process (PID=59488) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:38:51.873-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:38:51.875-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:38:51.874-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:38:52.191-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:38:52.187-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:38:52.194-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:38:52.848-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.987 seconds
[2024-10-14T17:39:23.507-0600] {processor.py:186} INFO - Started process (PID=59583) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:39:23.509-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:39:23.511-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:39:23.511-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:39:23.882-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:39:23.878-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:39:23.887-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:39:24.129-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.631 seconds
[2024-10-14T17:39:54.386-0600] {processor.py:186} INFO - Started process (PID=59678) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:39:54.418-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:39:54.421-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:39:54.420-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:39:54.952-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:39:54.947-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:39:54.955-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:39:55.292-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.922 seconds
[2024-10-14T17:40:25.478-0600] {processor.py:186} INFO - Started process (PID=59770) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:40:25.482-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:40:25.491-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:40:25.490-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:40:25.944-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:40:25.940-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:40:25.950-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:40:26.119-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.657 seconds
[2024-10-14T17:40:57.727-0600] {processor.py:186} INFO - Started process (PID=59862) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:40:57.757-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:40:57.759-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:40:57.759-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:40:58.127-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:40:58.123-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:40:58.131-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:40:58.303-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.595 seconds
[2024-10-14T17:41:29.571-0600] {processor.py:186} INFO - Started process (PID=59960) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:41:29.572-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:41:29.574-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:41:29.574-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:41:29.960-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:41:29.956-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:41:29.964-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:41:30.147-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.582 seconds
[2024-10-14T17:42:00.243-0600] {processor.py:186} INFO - Started process (PID=60052) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:42:00.251-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:42:00.253-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:42:00.253-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:42:00.759-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:42:00.755-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:42:00.762-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:42:00.938-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.701 seconds
[2024-10-14T17:42:31.983-0600] {processor.py:186} INFO - Started process (PID=60144) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:42:31.985-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:42:31.987-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:42:31.987-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:42:32.341-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:42:32.336-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:42:32.344-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:42:32.614-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.639 seconds
[2024-10-14T17:43:03.092-0600] {processor.py:186} INFO - Started process (PID=60236) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:43:03.093-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:43:03.096-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:43:03.095-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:43:03.575-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:43:03.560-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:43:03.581-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:43:03.771-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.694 seconds
[2024-10-14T17:43:34.524-0600] {processor.py:186} INFO - Started process (PID=60328) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:43:34.532-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:43:34.534-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:43:34.533-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:43:34.913-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:43:34.908-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:43:34.917-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:43:35.103-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.585 seconds
[2024-10-14T17:44:05.825-0600] {processor.py:186} INFO - Started process (PID=60426) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:44:05.826-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:44:05.833-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:44:05.832-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:44:06.252-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:44:06.247-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:44:06.255-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:44:06.435-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.621 seconds
[2024-10-14T17:44:36.846-0600] {processor.py:186} INFO - Started process (PID=60518) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:44:36.852-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:44:36.855-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:44:36.854-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:44:37.211-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:44:37.207-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:44:37.214-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:44:37.778-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.940 seconds
[2024-10-14T17:45:08.759-0600] {processor.py:186} INFO - Started process (PID=60610) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:45:08.761-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:45:08.764-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:45:08.763-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:45:09.120-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:45:09.116-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:45:09.123-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:45:09.303-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.549 seconds
[2024-10-14T17:45:39.714-0600] {processor.py:186} INFO - Started process (PID=60702) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:45:39.728-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:45:39.730-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:45:39.730-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:45:40.084-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:45:40.080-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:45:40.087-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:45:40.253-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.546 seconds
[2024-10-14T17:46:10.419-0600] {processor.py:186} INFO - Started process (PID=60794) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:46:10.429-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:46:10.432-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:46:10.431-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:46:10.803-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:46:10.797-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:46:10.810-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:46:11.192-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.779 seconds
[2024-10-14T17:46:42.102-0600] {processor.py:186} INFO - Started process (PID=60886) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:46:42.112-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:46:42.114-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:46:42.114-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:46:42.460-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:46:42.455-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:46:42.463-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:46:42.655-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.560 seconds
[2024-10-14T17:47:12.837-0600] {processor.py:186} INFO - Started process (PID=60978) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:47:12.848-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:47:12.851-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:47:12.850-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:47:13.221-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:47:13.217-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:47:13.224-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:47:15.040-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 2.211 seconds
[2024-10-14T17:47:45.231-0600] {processor.py:186} INFO - Started process (PID=61076) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:47:45.232-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:47:45.234-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:47:45.233-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:47:45.628-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:47:45.621-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:47:45.632-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:47:45.877-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.663 seconds
[2024-10-14T17:48:16.013-0600] {processor.py:186} INFO - Started process (PID=61168) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:48:16.029-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:48:16.034-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:48:16.033-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:48:16.563-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:48:16.560-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:48:16.572-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:48:16.757-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.759 seconds
[2024-10-14T17:48:46.887-0600] {processor.py:186} INFO - Started process (PID=61260) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:48:46.889-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:48:46.893-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:48:46.892-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:48:47.279-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:48:47.275-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:48:47.282-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:48:47.642-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.765 seconds
[2024-10-14T17:49:17.768-0600] {processor.py:186} INFO - Started process (PID=61352) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:49:17.787-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:49:17.789-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:49:17.789-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:49:18.253-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:49:18.250-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:49:18.256-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:49:18.429-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.667 seconds
[2024-10-14T17:49:49.120-0600] {processor.py:186} INFO - Started process (PID=61444) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:49:49.120-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:49:49.123-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:49:49.122-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:49:49.549-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:49:49.543-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:49:49.553-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:49:49.890-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.776 seconds
[2024-10-14T17:50:20.202-0600] {processor.py:186} INFO - Started process (PID=61536) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:50:20.286-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:50:20.289-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:50:20.289-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:50:20.703-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:50:20.697-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:50:20.717-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:50:20.994-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.804 seconds
[2024-10-14T17:50:51.097-0600] {processor.py:186} INFO - Started process (PID=61628) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:50:51.099-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:50:51.102-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:50:51.102-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:50:51.483-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:50:51.480-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:50:51.488-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:50:51.665-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.574 seconds
[2024-10-14T17:51:21.824-0600] {processor.py:186} INFO - Started process (PID=61724) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:51:21.834-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:51:21.836-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:51:21.836-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:51:22.371-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:51:22.364-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:51:22.374-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:51:22.691-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.877 seconds
[2024-10-14T17:51:52.878-0600] {processor.py:186} INFO - Started process (PID=61810) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:51:52.879-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:51:52.888-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:51:52.884-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:51:53.586-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:51:53.580-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:51:53.596-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:51:54.589-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.728 seconds
[2024-10-14T17:52:24.746-0600] {processor.py:186} INFO - Started process (PID=61902) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:52:24.755-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:52:24.757-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:52:24.757-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:52:25.270-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:52:25.265-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:52:25.274-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:52:25.501-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.760 seconds
[2024-10-14T17:52:55.765-0600] {processor.py:186} INFO - Started process (PID=61994) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:52:55.774-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:52:55.778-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:52:55.778-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:52:56.292-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:52:56.288-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:52:56.295-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:52:56.549-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.799 seconds
[2024-10-14T17:53:26.750-0600] {processor.py:186} INFO - Started process (PID=62092) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:53:26.751-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:53:26.753-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:53:26.753-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:53:27.099-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:53:27.094-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:53:27.103-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:53:27.631-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.887 seconds
[2024-10-14T17:53:57.666-0600] {processor.py:186} INFO - Started process (PID=62184) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:53:57.667-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:53:57.669-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:53:57.669-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:53:58.022-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:53:58.018-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:53:58.025-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:53:58.232-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.574 seconds
[2024-10-14T17:54:28.360-0600] {processor.py:186} INFO - Started process (PID=62273) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:54:28.386-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:54:28.388-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:54:28.388-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:54:28.825-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:54:28.821-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:54:28.828-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:54:28.996-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.649 seconds
[2024-10-14T17:54:59.126-0600] {processor.py:186} INFO - Started process (PID=62362) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:54:59.127-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:54:59.129-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:54:59.128-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:54:59.928-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:54:59.912-0600] {dagbag.py:387} ERROR - Failed to import: /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
Traceback (most recent call last):
  File "/home/victor_castellanosv/newsapi_project/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py", line 30, in <module>
    python_callable=fetch_news,
NameError: name 'fetch_news' is not defined
[2024-10-14T17:54:59.943-0600] {processor.py:927} WARNING - No viable dags retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:55:00.159-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 1.040 seconds
[2024-10-14T17:55:18.640-0600] {processor.py:186} INFO - Started process (PID=62424) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:55:18.993-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:55:18.996-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:18.996-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:55:19.530-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:55:21.284-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:21.283-0600] {override.py:1907} INFO - Created Permission View: can delete on DAG:newsapi_dag
[2024-10-14T17:55:21.454-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:21.453-0600] {override.py:1907} INFO - Created Permission View: can edit on DAG:newsapi_dag
[2024-10-14T17:55:21.611-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:21.611-0600] {override.py:1907} INFO - Created Permission View: can read on DAG:newsapi_dag
[2024-10-14T17:55:22.052-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:22.052-0600] {override.py:1907} INFO - Created Permission View: menu access on DAG Run:newsapi_dag
[2024-10-14T17:55:22.229-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:22.228-0600] {override.py:1907} INFO - Created Permission View: can delete on DAG Run:newsapi_dag
[2024-10-14T17:55:22.405-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:22.404-0600] {override.py:1907} INFO - Created Permission View: can create on DAG Run:newsapi_dag
[2024-10-14T17:55:22.765-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:22.764-0600] {override.py:1907} INFO - Created Permission View: can read on DAG Run:newsapi_dag
[2024-10-14T17:55:22.765-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:22.765-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:55:22.775-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:22.775-0600] {dag.py:3262} INFO - Creating ORM DAG for newsapi_dag
[2024-10-14T17:55:22.785-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:22.785-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:55:23.641-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 5.012 seconds
[2024-10-14T17:55:53.929-0600] {processor.py:186} INFO - Started process (PID=62530) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:55:53.931-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:55:53.934-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:53.933-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:55:54.281-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:55:54.298-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:54.297-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:55:54.408-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:55:54.408-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:55:54.576-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.653 seconds
[2024-10-14T17:56:24.734-0600] {processor.py:186} INFO - Started process (PID=62622) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:56:24.735-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:56:24.738-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:56:24.737-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:56:25.188-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:56:25.303-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:56:25.303-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:56:25.323-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:56:25.322-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:56:25.502-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.773 seconds
[2024-10-14T17:56:55.637-0600] {processor.py:186} INFO - Started process (PID=62714) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:56:55.653-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:56:55.656-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:56:55.656-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:56:56.085-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:56:56.200-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:56:56.199-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:56:56.216-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:56:56.216-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:56:56.384-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.754 seconds
[2024-10-14T17:57:26.548-0600] {processor.py:186} INFO - Started process (PID=62806) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:57:26.549-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:57:26.551-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:57:26.551-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:57:26.922-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:57:27.073-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:57:27.072-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:57:27.115-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:57:27.115-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:57:27.376-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.835 seconds
[2024-10-14T17:57:57.522-0600] {processor.py:186} INFO - Started process (PID=62898) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:57:57.536-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:57:57.538-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:57:57.538-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:57:57.903-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:57:57.923-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:57:57.923-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:57:57.952-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:57:57.951-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:57:58.126-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.611 seconds
[2024-10-14T17:58:30.637-0600] {processor.py:186} INFO - Started process (PID=62998) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:58:30.639-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:58:30.645-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:58:30.642-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:58:31.075-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:58:31.105-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:58:31.104-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:58:31.125-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:58:31.125-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:58:31.561-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.932 seconds
[2024-10-14T17:59:01.811-0600] {processor.py:186} INFO - Started process (PID=63097) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:59:01.811-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:59:01.817-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:59:01.815-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:59:02.461-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:59:02.491-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:59:02.490-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:59:02.518-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:59:02.518-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:59:04.111-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 2.308 seconds
[2024-10-14T17:59:35.517-0600] {processor.py:186} INFO - Started process (PID=63201) to work on /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:59:35.528-0600] {processor.py:914} INFO - Processing file /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py for tasks to queue
[2024-10-14T17:59:35.531-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:59:35.531-0600] {dagbag.py:588} INFO - Filling up the DagBag from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:59:35.979-0600] {processor.py:925} INFO - DAG(s) 'newsapi_dag' retrieved from /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py
[2024-10-14T17:59:36.001-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:59:36.001-0600] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-14T17:59:36.028-0600] {logging_mixin.py:190} INFO - [2024-10-14T17:59:36.028-0600] {dag.py:4180} INFO - Setting next_dagrun for newsapi_dag to 2024-10-14 00:00:00+00:00, run_after=2024-10-15 00:00:00+00:00
[2024-10-14T17:59:36.365-0600] {processor.py:208} INFO - Processing /home/victor_castellanosv/newsapi_project/airflow/dags/newsapi_dag.py took 0.855 seconds
